name: Walmart Monitor

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      PRODUCT_URL: ${{ vars.PRODUCT_URL }}
      SMTP_SERVER: ${{ vars.SMTP_SERVER }}
      SMTP_PORT: ${{ vars.SMTP_PORT }}
      FROM_EMAIL: ${{ vars.FROM_EMAIL }}
      TO_EMAIL: ${{ vars.TO_EMAIL }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test Email Connectivity
        run: python test_email.py
      - name: Run Walmart Monitor
        run: python walmart_monitor.py 